In [96]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

Daily DoR for AAPL

In [97]:
tick = "AAPL"
ticker = yf.Ticker(tick)
data = ticker.history(period = "max")
print(data)

                                 Open        High         Low       Close  \
Date
1980-12-12 00:00:00-05:00    0.098122    0.098549    0.098122    0.098122
1980-12-15 00:00:00-05:00    0.093430    0.093430    0.093003    0.093003
1980-12-16 00:00:00-05:00    0.086604    0.086604    0.086177    0.086177
1980-12-17 00:00:00-05:00    0.088310    0.088737    0.088310    0.088310
1980-12-18 00:00:00-05:00    0.090870    0.091297    0.090870    0.090870
...                               ...         ...         ...         ...
2026-08-31 00:00:00-04:00  319.600006  321.239990  312.799988  316.850006
2026-09-01 00:00:00-04:00  316.980011  327.299988  314.730011  325.130005
2026-09-02 00:00:00-04:00  326.869995  328.399994  323.529999  324.959991
2026-09-03 00:00:00-04:00  324.869995  330.809998  324.109985  328.209991
2026-09-04 00:00:00-04:00  328.309998  328.929993  317.859985  319.970001

                              Volume  Dividends  Stock Splits
Date
1980-12-12 00:00:00-05:00  469033600        0.0           0.0
1980-12-15 00:00:00-05:00  175884800        0.0           0.0
1980-12-16 00:00:00-05:00  105728000        0.0           0.0
1980-12-17 00:00:00-05:00   86441600        0.0           0.0
1980-12-18 00:00:00-05:00   73449600        0.0           0.0
...                              ...        ...           ...
2026-08-31 00:00:00-04:00   41242700        0.0           0.0
2026-09-01 00:00:00-04:00   53167400        0.0           0.0
2026-09-02 00:00:00-04:00   33776400        0.0           0.0
2026-09-03 00:00:00-04:00   37225800        0.0           0.0
2026-09-04 00:00:00-04:00   39551800        0.0           0.0

[11525 rows x 7 columns]

In [98]:
df = pd.DataFrame(data)
df = df.reset_index()
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.0,0.0
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.0,0.0
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.0,0.0
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.0,0.0
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,41242700,0.0,0.0
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,53167400,0.0,0.0
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,33776400,0.0,0.0
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,37225800,0.0,0.0
11524,2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001,39551800,0.0,0.0

In [99]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11525 entries, 0 to 11524
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          11525 non-null  datetime64[s, America/New_York]
 1   Open          11525 non-null  float64
 2   High          11525 non-null  float64
 3   Low           11525 non-null  float64
 4   Close         11525 non-null  float64
 5   Volume        11525 non-null  int64
 6   Dividends     11525 non-null  float64
 7   Stock Splits  11525 non-null  float64
dtypes: datetime64[s, America/New_York](1), float64(6), int64(1)
memory usage: 720.4 KB

In [100]:
df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,11525.000000,11525.000000,11525.000000,11525.000000,1.152500e+04,11525.000000,11525.000000
mean,31.654362,32.001550,31.332176,31.681647,3.058985e+08,0.000920,0.001475
std,65.098495,65.816578,64.453487,65.168515,3.324280e+08,0.013561,0.081728
min,0.037969,0.037969,0.037542,0.037542,0.000000e+00,0.000000,0.000000
25%,0.249558,0.254294,0.243016,0.249558,1.035688e+08,0.000000,0.000000
50%,0.564544,0.576228,0.552393,0.565011,1.949948e+08,0.000000,0.000000
75%,22.745346,23.005600,22.641614,22.840563,3.856720e+08,0.000000,0.000000
max,339.736982,344.273097,337.059318,339.786926,7.421641e+09,0.270000,7.000000

In [101]:
df.to_csv("AAPL_DoR_Daily")

In [102]:
df = df.drop(columns= "Dividends")
df = df.drop(columns= "Stock Splits")
df = df.drop(columns= "Volume")

In [103]:
df = df.sort_values(by= "Date", ascending=False)
df

,Date,Open,High,Low,Close
11524,2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006
...,...,...,...,...,...
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122

In [104]:
df["O-C Returns"] = ((df["Close"] - df["Open"])/df["Open"])*100
df["H-L Returns"] = ((df["High"] - df["Low"])/df["Low"])*100
df

,Date,Open,High,Low,Close,O-C Returns,H-L Returns
11524,2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001,-2.540281,3.482668
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,1.028102,2.067203
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,-0.584331,1.505268
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,2.571138,3.993892
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,-0.860451,2.698211
...,...,...,...,...,...,...,...
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,0.000000,0.469449
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,0.000000,0.483066
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,-0.492577,0.495016
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,-0.456594,0.458689
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,0.000000,0.434758

In [105]:
df['C-C Returns'] = df['Close'].pct_change() * 100
df

,Date,Open,High,Low,Close,O-C Returns,H-L Returns,C-C Returns
11524,2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001,-2.540281,3.482668,NaN
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,1.028102,2.067203,2.575238
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,-0.584331,1.505268,-0.990220
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,2.571138,3.993892,0.052318
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,-0.860451,2.698211,-2.546673
...,...,...,...,...,...,...,...,...
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,0.000000,0.469449,-5.751872
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,0.000000,0.483066,-2.817542
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,-0.492577,0.495016,-2.415334
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,-0.456594,0.458689,7.921204
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,0.000000,0.434758,5.504214

In [106]:
df.isna().value_counts()

Date   Open   High   Low    Close  O-C Returns  H-L Returns  C-C Returns
False  False  False  False  False  False        False        False          11524
                                                             True               1
Name: count, dtype: int64

In [107]:
df = df.dropna()
df

,Date,Open,High,Low,Close,O-C Returns,H-L Returns,C-C Returns
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,1.028102,2.067203,2.575238
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,-0.584331,1.505268,-0.990220
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,2.571138,3.993892,0.052318
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,-0.860451,2.698211,-2.546673
11519,2026-08-28 00:00:00-04:00,316.850006,322.369995,315.450012,319.700012,0.899481,2.193686,0.899481
...,...,...,...,...,...,...,...,...
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,0.000000,0.469449,-5.751872
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,0.000000,0.483066,-2.817542
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,-0.492577,0.495016,-2.415334
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,-0.456594,0.458689,7.921204
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,0.000000,0.434758,5.504214